### ISSUE TITLE
All offset columns are generated as "g-offset1"

### ISSUE THREAD

**Issue by nicbell** [TryKickoff/kickoff#15]
It looks like all offsets are being generated as `g-offset1`.
The bug is on [line 121 of  _choreographic-grid.scs](https://github.com/tmwagency/kickoff/blob/master/scss/partials/components/_choreographic-grid.scss#L121)
`.g-row > .g-offset1 {` the '1' should be dynamic. 

This is the current output.

``` CSS
    .g-row > .g-offset1 {
        margin-left: 0.03157895%;
    }

    .g-row > .g-offset1:first-child {
        margin-left: 10.03157895;
    }

    .g-row > .g-offset1 {
        margin-left: 0.14736842%;
    }

    .g-row > .g-offset1:first-child {
        margin-left: 20.14736842;
    }
```
