### ISSUE TITLE
Type sizing

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#62]
I saw on Dropbox's Scooter framework, that they have helper classes for type size. We have kind of have this at the moment with our headings:

```scss
// Use the helper classes to emulate styles for another element
// For example: h3.h1 or h3.alpha
h1, .h1, .alpha {
	@include font-size($type-largest);
	margin-bottom: $baseline * 2;
}

h2, .h2, .beta {
	@include font-size($type-large);
}

h3, .h3, .gamma {
	@include font-size($type-mid);
}

h4, .h4, .delta {
	@include font-size($type-base);
}

h5, .h5, .epsilon,
h6, .h6, .zeta {
	@include font-size($type-small);
	margin-bottom: 0;
}
```

What do you think of removing the helper classes from the above and making more generi classes like below:
```scss
/**
 * Type sizes
 */
.type-micro    { @include font-size($type-micro); }
.type-smallest { @include font-size($type-smallest); }
.type-smaller  { @include font-size($type-smaller); }
.type-small    { @include font-size($type-small); }
.type-base     { @include font-size($type-base); }
.type-mid      { @include font-size($type-mid); }
.type-large    { @include font-size($type-large); }
.type-largest  { @include font-size($type-largest); }
.type-jumbo    { @include font-size($type-jumbo); }
```

We could even have this so it is made perfectly clear what sizes each element uses:

```scss
/**
 * Type sizes
 */
.type-micro         { @include font-size($type-micro); }
.type-smallest      { @include font-size($type-smallest); }
.type-smaller       { @include font-size($type-smaller); }
.type-small, h5, h6 { @include font-size($type-small); }
.type-base, p, h4   { @include font-size($type-base); }
.type-mid, h3       { @include font-size($type-mid); }
.type-large, h2     { @include font-size($type-large); }
.type-largest, h1   { @include font-size($type-largest); }
.type-jumbo         { @include font-size($type-jumbo); }
```

Which would ultimately look something like this:

```scss
/**
 * Paragraphs
 */
p {
	font-family: $font-family-base;
	margin-top: 0;
	margin-bottom: $baseline;

	// Measure - ideally about 65 chars per line
	// max-width: $type-base * 30 + px;

	// & small {
	// 	color: lighten($color-text, 10%);
	// }
}

/**
 * Headings
 */
h1, h2, h3, h4, h5, h6 {
	margin: 0;
	font-family: $font-family-headings;
	font-weight: $font-weight-headings;
	line-height: $line-height-headings;
	text-rendering: optimizelegibility; // Fix the character spacing for headings
	margin-top: 0;
	margin-bottom: $baseline;

	small {
		font-weight: normal;
	}
}

// Use the helper classes to emulate styles for another element
// For example: h3.h1 or h3.alpha
h1 {
	margin-bottom: $baseline * 2;
}

h5
h6 {
	margin-bottom: 0;
}

// Only give these headings a margin-top if they are after other elements
* + h1, * + .h1, * + .alpha,
* + h2, * + .h2, * + .beta,
* + h3, * + .h3, * + .gamma,
* + h4, * + .h4, * + .delta {
	margin-top: $baseline;
}

small {
	font-size: 80%;
}

/**
 * Type sizes
 */
.type-micro                { @include font-size($type-micro); }
.type-smallest             { @include font-size($type-smallest); }
.type-smaller              { @include font-size($type-smaller); }
.type-small, h5, h6, small { @include font-size($type-small); }
.type-base, p, h4          { @include font-size($type-base); }
.type-mid, h3              { @include font-size($type-mid); }
.type-large, h2            { @include font-size($type-large); }
.type-largest, h1          { @include font-size($type-largest); }
.type-jumbo                { @include font-size($type-jumbo); }
```

Would love some feedback on this please @munkychop @ciaranpark @ashleynolan @nicbell
